pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'make'
            }
        }
        stage('Test') {
            steps {
                sh 'build'
            }
        }
        stage('Deploy') {
            steps {
                sh 'deploy'
            }
        }
    }
}